name: respix
description: An extremely simple, intuitive API for building fully responsive Flutter applications across mobile, tablet, laptop, desktop, and web layouts.
version: 0.0.2
homepage: https://github.com/Nikhill437/respix
repository: https://github.com/Nikhill437/respix
issue_tracker: https://github.com/Nikhill437/respix/issues
documentation: https://github.com/Nikhill437/respix#readme

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

topics:
  - responsive
  - ui
  - layout
  - widgets
  - breakpoints

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
